cxx_compiler:           # [win]
  - vs2019              # [win]
c_compiler:             # [win]
  - vs2019              # [win]
gpu_variant:
  #- cuda-11                    # [linux and x86_64]
  - cuda-12                    # [linux and x86_64]
  - cuda-12                    # [win and x86_64]
# Only needed for cuda-11
cudatoolkit:
  - 11.8
cuda_compiler_version:
  - 12.8
mkl:
  - 2025
